server:
  port: '8084'
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: >-
      jdbc:mysql://localhost:3306/employee_payroll_app?createDatabaseIfNotExist=true
    password: Tanuja@99
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

